baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'GadFly'

[params]

  [[params.navlinks]]
  name = "Home"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"

  [[params.navlinks]]
  name = "Contact"
  url = "contact/"